### ISSUE TITLE
4.3.2 More config options when creating new results parser

### ISSUE THREAD

**Issue by monicaseing** [platify/platify#13]
New features:
1) User should be able to specify the assay type (HTS, dose response, std curve, qtPCR).
2) User should be able to specify plate size.

This is so the results parser can be filtered by these settings, as there may be hundreds of parsers.

Req. 3.2

**Comment by henstockpv** [comment]
This seems to be a combination of filtering to find existing parsers that have been defined, and the start of a new one.  The start of a new one may just be through the UI so this step may turn into just a filtering of characteristics of defined parsers.

**Comment by vinodhalaharvi** [comment]
@monicaseing; Making myself  assignee based on your comment on slack
