### ISSUE TITLE
4.5.13 Export of data to file at every step of assay workflow

### ISSUE THREAD

**Issue by monicaseing** [platify/platify#25]

**Comment by reagan83** [comment]
@monicaseing: Just to confirm - is this part of req 4.5.13?

**Comment by monicaseing** [comment]
This covers Req. 4.5.13 (export processed results), but it is a general requirement for all other points of the assay workflow too (should be able to export files of created plate, parsed results, normalized results, etc.). 

I aggregated them into one issue because they basically go through the same process of generating a file based on the user's specified format (using the flexible parser that Ryan wants to create).
