### ISSUE TITLE
 Generate heat map

### ISSUE THREAD

**Issue by vinodhalaharvi** [platify/platify#29]

**Comment by monicaseing** [comment]
Vinod, this is covered in issue 1. I believe you volunteered to port the heatmap from WestEast, correct?

**Comment by REMitchell** [comment]
I might be misunderstanding something, but there's already a heat map here? http://localhost:8080/platify/result/showactions/1

**Comment by monicaseing** [comment]
There is, but the WestEast one has more features, like knocking out a wells (a requirement)and viewing multiple plates of a plate set. I am thinking maybe we could keep our heat map for now and, if there is time, we'll bring in the heatmap from WestEast.

**Comment by vinodhalaharvi** [comment]
Monica,

OK sounds good. As mentioned in the meeting, I was literally going by the
issue points from the word doc. You seem to have done a very thorough work,
great job!

Yes, you may work on it  and I will find something else to work on :).
Please remove me from assignee and put your name against it.

thanks
Vinod Halaharvi

**Comment by monicaseing** [comment]
Vinod,

I think you misread my message. I was just asking if you volunteered to work on it, not that I am volunteering. :)

**Comment by vinodhalaharvi** [comment]
Monica,

Yes, you are right ! I mis read it;  I as reading the message on the metro
trying to hold on the bar dearly all the while reading emails on my cell
:).

I will take it and assign it to myself.

-Vinod

**Comment by vinodhalaharvi** [comment]
Monica, you closed #29, is the work done? please clarify.

**Comment by monicaseing** [comment]
As mentioned above, this is a repeat of issue #1 .

**Comment by vinodhalaharvi** [comment]
Just to clarify, I am only asking because there was a confusion between us
as to who is going to do the work ..

**Comment by vinodhalaharvi** [comment]
I see got it thanks!
