### ISSUE TITLE
4.4.2 View control values per plate in scatterplot (plate vs. positive & negative control values)

### ISSUE THREAD

**Issue by vinodhalaharvi** [platify/platify#30]

**Comment by reagan83** [comment]
@vinodhalaharvi what req is this bound to?

**Comment by vinodhalaharvi** [comment]
Team,

I don't see any assignees (except me and Reagan and Caleb) next to the
issues. I have assigned myself to three issues, if someone else is working
on it *please* let me know so we don't duplicate work.

Also please make sure to put yourself in the assignee list  before you
start the work.

-Vinod

**Comment by vinodhalaharvi** [comment]
Reagan,  It's from  4.4.2

**Comment by monicaseing** [comment]
![scatterplot_controlsperplate](https://cloud.githubusercontent.com/assets/10761754/14574272/907d7a8c-0328-11e6-8a39-57671c9528b5.png)
